version: "3.9"

services:
  edge-proxy:
    build: ./edge_proxy
    ports:
      - "9443:443"
    depends_on:
      - api-service
    networks:
      - private_net

  api-service:
    build: ./api_service
    expose:
      - "7000"
    depends_on:
      - storage
    networks:
      - private_net

  storage:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./storage/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro
    networks:
      - private_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - private_net

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - private_net

networks:
  private_net:

volumes:
  db_volume:
  grafana_data:
